---
title: "About Me"
output:
  html_document:
    toc: true
    toc_float: true

---

I completed my PhD at Goldsmiths, Univesity of London in December 2016. My thesis investigated the neural correlates of motor learning in adults with and without DCD.

I am a Postdoctoral fellow currently working at the University of Surrey in the [School of Psychology](https://www.surrey.ac.uk/school-psychology).
I am working with [Dr. Hayley Leonard](https://www.surrey.ac.uk/people/hayley-leonard) and [Prof. Bertram Opitz](https://www.surrey.ac.uk/people/bertram-opitz) on a project investigating sequence predction in typically developing children, children with Developmental coordination disorder (DCD), and children with both DCD and language difficulties.

---

##Education {#education}  
**Ph.D. Psychology** - *Department of Psychology, Goldsmiths: 10/2012 - 09/2016*  

* Funded by Departmental Studentship
* Awarded with no corrections
* Supervised by Dr. Jose Van Velzen & Prof. Elisabeth Hill

**M.Sc. Cognitive and Clinical Neuroscience** - *Department of Psychology, Goldsmiths: 10/2010 - 09/2012*

* Awarded with Merit

**B.Sc. (Hons.) Psychology with Neuroscience** - *Faculty of Science and Technology, University of Westminster: 10/2007 - 06/2010*

* Awarded Upper Second-Class honours

---

##Employment {#employment}

**Postdoctoral research fellow (80% FTE)** - *School of Psychology, University of Surrey: 10/2017 - Present*

* Principle Investigators: Dr. Hayley Leonard & Prof. Bertram Opitz

**Postdoctoral research fellow (60% FTE)** - *Centre for Brain & Cognitive Development, Department of Psychological Sciences, Birkbeck: 04/2016 - 09/2017*

* Infant stream of the London Down Syndrome (LonDownS) Consortium
* Supervised by Prof. Michael Thomas & Prof. Denis Mareschal (formerly supervised by Prof. Karmiloff-Smith)

**Associate Lecturer** - *Department of Psychology, Goldsmiths: 10/2012 - 04/2016*

* Teaching 1st and 2nd year undergraduate tutorials
* 3rd year undergraduate and M.Sc. hands-on demonstrations with neuroscientific equipment
* E-Prime support space

---

##Skills {#skills}

**Technical skills**:
  
* Programming: *Matlab, Python and R*
* Experimental design: *PsychoPy, Psychtoolbox, E-Prime*
* Experimental equipment: *EEG, TMS, and Eyetracking* 
* Data analysis: *Behavioural, EEG, and Eyetracking*
* Testing children and adults

